#ifndef _NTW_CLIENT_H
#define _NTW_CLIENT_H

#include <iostream>
#include <vector>
#include <QTcpSocket>

#include "Player.hh"
#include "Map.hh"

/**
 * @brief The Client class
 * Class used to manage Client socket connections from the Server.
 * NOT INTENTED TO BE USED BY THE "CLIENT" PART OF THE Zappy PROJECT !!
 */
class Client
{

public:
    Client();
    ~Client();
    Client(QString client_id, QTcpSocket *socket);
    Client(std::string client_id, QTcpSocket *socket);

    void setPlayer(Player* player);
    Player* getPlayer();
    void setMap(Map* map);
    Map* getMap();

    void setClientId(QString client_id);
    QString getClientId();

    void setCommand(QString command);       // Sets the next command to play
    QString getCommand();                   // Returns the next command to play
    void clearCommand();                    // Clears the command saved

    void disconnect();                      // Drops the socket connection
    QTcpSocket* getSocket();
    bool isConnected();

private:
    QTcpSocket *socket = nullptr;
    QString client_id = NULL;               // generated by the server

    Map* map;                               // Pointing to associated map
    Player* player;                         // Pointing to associated player
    QString move_command = "";              // next move command to play
};

#endif
