#ifndef _NTW_CLIENT_H
#define _NTW_CLIENT_H

#include <iostream>
#include <vector>
#include <QTcpSocket>

/**
 * @brief The Client class
 * Class used to manage Client socket connections from the Server.
 * NOT INTENTED TO BE USED BY THE "CLIENT" PART OF THE Zappy PROJECT !!
 */
class Client
{

public:
    Client();
    ~Client();
    Client(QString client_id, QTcpSocket *socket);
    Client(std::string client_id, QTcpSocket *socket);

    // Local resources
    bool connect(QString host_address, QString host_port); // Returns the success state
    void disconnect();                      // Drops the socket connection
    void setClientId(QString client_id);
    QString getClientId();
    QTcpSocket* getSocket();
    void addCommand(QString command);       // Adds a command to the top of the stack
    QString readCommand();                  // Unstacks and returns the oldest command
    bool connected = false;

private:
    QTcpSocket *socket = nullptr;
    QString client_id = NULL;               // generated by the server

    std::vector<QString> commands_stack;    // stack of commands sent or received
    long last_game_cycle = -1;
};

#endif
